
server: 
  port: ${SERVER_PORT:9001}
spring:
  application: 
    name: config-server 
  cloud:
    config:
      server:        
        git:
          uri: https://${git_host:github.com}:${git_port:443}/${git_org:happycloudpak}/${git_repo:config-svcmesh.git}
          username: ${git_id:happycloudpak}
          password: ${git_pw:happy@cloud0}                            
          search-paths: /          #base directory to search profiles
          default-label: ${git_branch:main}      #git branch

# Spring cloud bus #
# 참고: https://coe.gitbook.io/guide/config/springcloudconfigbus
 
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
rabbitmq:
  host: ${mq_host:localhost}
  port: ${mq_port:5672}
  username: ${mq_id:guest}
  password: ${mq_pw:guest}